### ISSUE TITLE
Opensource?

### ISSUE THREAD

**Issue by Xiaoyang-Rebecca** [VoidChen/CG_final#1]
Hi @VoidChen , 
I am Rebecca Li from Adobe Inc, I am currently building an  augmentation library (will be open source soon) and your palette recolording looks like a stable implementation of this paper: https://gfx.cs.princeton.edu/pubs/Chang_2015_PPR/chang2015-palette_small.pdf 

I was wondering if your repository could be open sourced.

If so, please add the MIT license to the root folder.

Feel free to ask me question.

**Comment by VoidChen** [comment]
OK 😃

**Comment by Xiaoyang-Rebecca** [comment]
Thanks! I will keep you informed when our library released.

**Comment by Xiaoyang-Rebecca** [comment]
Hi @VoidChen,
I included your implementation in the external resource of the open sourced package: [beacon_aug](https://adobe-research.github.io/beacon-aug/)

- load part of your source code
https://github.com/adobe-research/beacon-aug/blob/master/beacon_aug/external/Palette_recolor. 
- call it as an augmentation function
https://github.com/adobe-research/beacon-aug/blob/master/beacon_aug/generator/custom/PaletteRecolor.py

Feel free to let me know if you need to make any changes, or if you would like to add as contributor.
